server:
  port: 5001

spring:
  application:
    name: TASK-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: 2551
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/